/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'InternetCafe' : IDL.Null,
  'Electrical' : IDL.Null,
  'PhotoBinding' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const ShoppingItem = IDL.Record({
  'name' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const PaymentMethod = IDL.Variant({
  'COD' : IDL.Null,
  'UPI' : IDL.Null,
  'Card' : IDL.Null,
});
export const DeliveryType = IDL.Variant({
  'Delivery' : IDL.Null,
  'Pickup' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'Cancelled' : IDL.Null,
  'Processing' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'orderStatus' : OrderStatus,
  'deliveryType' : DeliveryType,
  'totalAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(CartItem),
  'customerEmail' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Complete' : IDL.Null,
  'Expired' : IDL.Null,
});
export const StripeConfiguration = IDL.Record({
  'secretKey' : IDL.Text,
  'publishableKey' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PaymentMethod,
        DeliveryType,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteAdminSetting' : IDL.Func([IDL.Text], [], []),
  'getAdminSetting' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getAllAdminSettings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getFounderPhotoHash' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFounderPhoto' : IDL.Func([], [], []),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'removeProduct' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setFounderPhoto' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'InternetCafe' : IDL.Null,
    'Electrical' : IDL.Null,
    'PhotoBinding' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const ShoppingItem = IDL.Record({
    'name' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const PaymentMethod = IDL.Variant({
    'COD' : IDL.Null,
    'UPI' : IDL.Null,
    'Card' : IDL.Null,
  });
  const DeliveryType = IDL.Variant({
    'Delivery' : IDL.Null,
    'Pickup' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'Cancelled' : IDL.Null,
    'Processing' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'orderStatus' : OrderStatus,
    'deliveryType' : DeliveryType,
    'totalAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(CartItem),
    'customerEmail' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'Open' : IDL.Null,
    'Complete' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const StripeConfiguration = IDL.Record({
    'secretKey' : IDL.Text,
    'publishableKey' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [], []),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PaymentMethod,
          DeliveryType,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteAdminSetting' : IDL.Func([IDL.Text], [], []),
    'getAdminSetting' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getAllAdminSettings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getFounderPhotoHash' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFounderPhoto' : IDL.Func([], [], []),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'removeProduct' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setFounderPhoto' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };