/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : string, 'quantity' : bigint }
export type Category = { 'InternetCafe' : null } |
  { 'Electrical' : null } |
  { 'PhotoBinding' : null };
export type DeliveryType = { 'Delivery' : null } |
  { 'Pickup' : null };
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'deliveryAddress' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'orderStatus' : OrderStatus,
  'deliveryType' : DeliveryType,
  'totalAmount' : bigint,
  'timestamp' : bigint,
  'customerId' : Principal,
  'items' : Array<CartItem>,
  'customerEmail' : string,
}
export type OrderStatus = { 'Cancelled' : null } |
  { 'Processing' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export type PaymentMethod = { 'COD' : null } |
  { 'UPI' : null } |
  { 'Card' : null };
export interface Product {
  'id' : string,
  'stockQuantity' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export interface ShoppingItem {
  'name' : string,
  'currency' : string,
  'quantity' : bigint,
  'amount' : bigint,
}
export interface StripeConfiguration {
  'secretKey' : string,
  'publishableKey' : string,
}
export type StripeSessionStatus = { 'Open' : null } |
  { 'Complete' : null } |
  { 'Expired' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<
    [string, string, string, PaymentMethod, DeliveryType, [] | [string]],
    bigint
  >,
  'deleteAdminSetting' : ActorMethod<[string], undefined>,
  'getAdminSetting' : ActorMethod<[string], [] | [string]>,
  'getAllAdminSettings' : ActorMethod<[], Array<[string, string]>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getFounderPhotoHash' : ActorMethod<[], [] | [Uint8Array]>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByCustomer' : ActorMethod<[string], Array<Order>>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeFounderPhoto' : ActorMethod<[], undefined>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'removeProduct' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminSetting' : ActorMethod<[string, string], undefined>,
  'setFounderPhoto' : ActorMethod<[Uint8Array], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];